config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products
  
  post 'static_pages/thank_you'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  resources :orders, only: [:index, :show, :create, :destroy]
  
  
  
  

  root 'static_pages#landing_page'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user (not logged in)
    can :manage, User, id: user.id
  end
end

    
    
    
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(rating: :asc) }
 
end

app/models/order.rb
class Order < ActiveRecord::Base 
    belongs_to :product
    belongs_to :user
end
#4.3 example shows ApplicationRecord, however, product.rb showed ActiveRecord::Base instead.
#Modifying 4.3 example from ApplicationRecord to ActiveRecord::Base

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :orders
    has_many :comments
    
    def self.search(search_term)
        if Rails.env.production?
            Product.where("name ILIKE ?", "%#{search_term}%")
        elsif Rails.env.development?
            Product.where("name LIKE ?", "%#{search_term}%")
        end
    end
    
    def highest_rating_comment 
        comments.rating_desc.first
    end
    
    def lowest_rating_comment 
        comments.rating_asc.first
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    has_many :orders
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end 

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController #this inherits all methods in application_controller.rb file

before_action :authenticate_user!
    
    def create
    end
    
    def index
    end
    
    def show
    end
    
    def new
    end
    
    def destroy
    end
    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

class PagesController < ApplicationController
    def show
        render template: "pages/#{params[:page]}"
    end
end  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products
  # GET /products.json


  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price) #but adding field on this line makes data visible on the product page.
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
  
  def landing_page
   @products = Product.limit(3)
  end
  
  
  def thank_you
   @name = params[:name]
   @email = params[:email]
   @message = params[:message]
   UserMailer.contact_form(@email, @name, @message).deliver_now
  end
end

#ActionMailer::Base.mail(from: @email,
     #to: 'joymajanil@gmail.com',
     #subject: "A new contact form message from #{@name}",
     #body: @message).deliver_now
  #end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A Dog's World</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Special+Elite">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  
</head>
<body>

<!-- Navigation -->	
	<nav class="my-navbar navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand navbar-brandfont">Woof! Gallery</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li class="active"> <%= link_to 'Home', root_path %></li>
	        <li><%= link_to 'Product', products_path %></li>
	        <li><%= link_to 'About', static_pages_about_path %></li>
	        <li><%= link_to 'Contact', static_pages_contact_path %></li>
	      </ul>
	      <ul class="nav pull-right">
	      	<li>
	      		<% if user_signed_in? %>
	      			<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
	      		<% else %>
	      			<%= link_to('Login', new_user_session_path) %>
	      		<% end %>
	      	</li>
	      </ul><!-- end nav pull right -->
	      
	      <div class="pull-right">
	      	<div class="navbar-form form-inline" role="search">
	      		<%= form_with(url: products_path, method: 'get', local: true) do |form| %>
  					<%= form.label :q, 'Search for:', hidden: 'true' %>
  					<%= form.text_field :q, id: 'q', value: params[:q], placeholder: 'Search' %>
  					<%= form.submit 'Search', class: 'btn'%>
						<% end %>	
					</div>
	      </div>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<!-- end of Navigation -->
	
	<% if notice %>
    <div id="notice-wrapper" class="alert alert-info"> 
     <p> <%= notice %> </p>
    </div>
  <% elsif alert %>
		<div id="notice-wrapper" class="alert alert-danger" role="alert">
			<p> <%= alert %> </p> 
		</div>
	<% end %>
	
	
	<%= yield %>
	
	<div class ="container-fluid">
		<footer class="site-footer">
	  	&copy; 2017 Woof! Gallery
		</footer>
	</div>
	
	</body>
	</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :colour %><br>
    <%= f.text_field :colour, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control" %>
  </div>
  <div class="actions btn">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/products/_product.html.erb
<div class ="col-sm-4">
  <p><%= image_tag(product.image_url, class: "img-responsive") unless product.image_url.blank? %></p>
  <h2><%= link_to product.name, product %></h2>
  <p>Description: <%= product.description %></p>
  <p>Colour: <%= product.colour %></p>
  <p>Price: <%= product.price %></p>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product) %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row" id="topspace">
    <%= render @products %>
  </div><!-- end row -->
  
  <%= link_to 'New Product', new_product_path %>
</div> <!-- end container-fluid -->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<article>
  <div>
    <p id="notice"><%= notice %></p>
    <div class="row"> <br></div>
    <div class="row">
      <div class="col-sm-6 col-md-6 col-md-offset-1">
        <p>
          <%= image_tag(@product.image_url, class: "img-responsive") %>
        </p>
      </div><!-- end colsm9 -->
         
      <div class="col-sm-4 col-md-4">
        <p> <strong>Name:</strong>
          <%= @product.name %>
        </p>
        
        <p>
          <strong>Description:</strong>
          <%= @product.description %>
        </p>
        
        <p>
          <strong>Image url:</strong>
          <%= @product.image_url %>
        </p>
        
        <p>
          <strong>Colour:</strong>
          <%= @product.colour %>
        </p>
        
        <p>
          <strong>Price:</strong>
          <%= @product.price %>
        </p>
        
        <p>
          <strong> Rating:</strong>
          <% if @product.highest_rating_comment %>
            <p><%= @product.highest_rating_comment.body %></p>
          <% end %>
        </p>
      </div>
    </div>
    
    <div class="col-md-offset-1">
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'Back', products_path %>
    </div>
    
  </div>

  
</article>

app/views/static_pages/about.html.erb
<div>
    
    <h1 class="abouttitle">Meet The Team</h1>
    <br>
    <div class="container">
        <div class ="row align-items-center">
            <div class="col-sm-4">
                <%= image_tag("contactdogpet", class: "img-responsive")%>    
                <h4>Rover 1</h4>
            </div>
            
            <div class="col-sm-4">
                <%= image_tag("contactdogpet", class: "img-responsive")%>
                <h4>Rover 1</h4>
            </div>
            
            <div class="col-sm-4">
                <%= image_tag("contactdogpet", class: "img-responsive")%>
                <h4>Rover 1</h4>
            </div>
        </div>
    </div>

</div>

app/views/static_pages/contact.html.erb
<p><%= image_tag("contactdogpet", class: "img-responsive fullimg")%></p>

<h1>Contact Us</h1>

<%= flash[:notice] %>

<%= form_with(url: "/static_pages/thank_you", local: true) do |form| %>
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %>
                
            </div>
            
            <div class="form-group">
                <%= form.label :email, "Email Address" %>
                <%= form.text_field :email, class: "form-control", placeholder: "Enter Email", required: true, type: "email" %>
            </div>
            
            <div class="form-group">
                <%= form.label :message %>
                <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", required: true %>
            </div>
        </div>
    </div>
    <%= form.submit "Send" %>
<% end %>

app/views/static_pages/index.html.erb
<!-- <h1>StaticPages#index</h1> -->
<!-- <p>Welcome! The date and time is %= Time.now %></p> -->
<!-- <h1>Adorable Dogs Gallery</h1> -->

    <div class="image-header">
		<%= image_tag("huskysnow.jpeg", class: "img-responsive") %>
		<h1 class="header-text">It's A Dog's <br> Life</h1>
	</div><!-- end image-header -->

	<div class="maincat-title">
		<h2>Check Out the Types of Dogs</h2>
	</div>

	<div class="container">
      <div class="row" id="maincategory">
        <div class="col-md-4 col-xs-6"><%= image_tag("Husky.jpg", class: "img-responsive") %> The Big Boys
        </div><!-- colmd3 -->
        
        <div class="col-md-4 col-xs-6"><%= image_tag("Corgi.jpeg", class: "img-responsive") %> Medium's My Middle Name
        </div><!-- colmd3 -->
        
        <div class="col-md-4 col-xs-6"><%= image_tag("puppy-yorkshire.jpeg", class: "img-responsive") %> Small but Mighty
        </div><!-- colmd3 -->
      </div><!-- end maincategory -->
      
      <div></div>
      <div></div>

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>

<!-- Carousel -->

<div id="carousel-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @products.each_with_index do |product, i| %>
    <li data-target="#carousel-generic" data-slide-to="#{i}" class="#{'active' if i == 0}" %> </li>
    <% end %>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item <%= "active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <div class="carousel-caption">
        <%= product.name %>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>